/**
 * Seeds a believable weekly timetable on top of the gym seed.
 *
 *   npm run seed:schedule
 *
 * Run after seed:gym — it looks up branches, class types and trainers by slug
 * and will tell you plainly if any are missing.
 *
 * Idempotent: rules are matched on the combination that makes one unique
 * (branch, class type, weekday, start time), so re-running updates rather than
 * duplicating. Sessions are generated by the same code the admin screen uses,
 * which is itself idempotent through a unique index.
 *
 * Pass --fresh to clear the timetable first. That deletes bookings too, so it
 * is a development convenience and nothing more.
 */
import { connect, disconnect, model } from 'mongoose';
import * as dotenv from 'dotenv';
import { Branch, BranchSchema } from '@/branches/schemas/branch.schema';
import { ClassType, ClassTypeSchema } from '@/class-types/schemas/class-type.schema';
import { Trainer, TrainerSchema } from '@/trainers/schemas/trainer.schema';
import {
  RecurrenceRule,
  RecurrenceRuleSchema,
  ClassSession,
  ClassSessionSchema,
} from '@/classes/schemas/class-session.schema';
import { Booking, BookingSchema } from '@/bookings/schemas/booking.schema';
import {
  zonedTimeToUtc,
  utcToZonedDate,
  utcToZonedWeekday,
  addLocalDays,
  GYM_TIMEZONE,
} from '@/common/utils/timezone.util';

dotenv.config();

const FRESH = process.argv.includes('--fresh');
const HORIZON_DAYS = 21;

// The shape of a real gym week: early mornings and evenings full, midday
// quieter, weekends later and lighter. Written per branch so the three sites
// do not look like copies of each other.
interface Slot {
  branch: string;
  classType: string;
  trainer: string | null;
  weekday: string;
  startTime: string;
  capacity?: number;
  room?: string;
  womenOnly?: boolean;
}

function weekdayRun(base: Omit<Slot, 'weekday'>, days: readonly string[]): Slot[] {
  return days.map(weekday => ({ ...base, weekday }));
}

// The gym's real weekly timetable, transcribed from the schedule it supplied.
//
// It runs on two alternating shapes. Saturday, Monday and Wednesday are the
// morning-heavy days; Sunday, Tuesday and Thursday are the evening ones. There
// is no Friday column — the gym runs no classes that day.
//
// TWO THINGS READ OFF THE IMAGE AND WORTH CONFIRMING:
//   1. The midday column is labelled "12:00 AM". Taken as 12:00 noon: it sits
//      between the 11:00 AM and 4:00 PM columns, and midnight belly dance is
//      not a thing the rest of the timetable supports.
//   2. Kick boxing appears at 4:00 PM on Saturday and Wednesday ONLY. Monday,
//      the third morning-shape day, has that cell empty.
//
// Trainers are unassigned — the timetable names classes, not coaches — so every
// rule is trainer: null and the gym can attach coaches in /admin/schedule.
// Rooms and women-only flags are likewise not on the supplied sheet.
const MORNING_DAYS = ['saturday', 'monday', 'wednesday'] as const;
const EVENING_DAYS = ['sunday', 'tuesday', 'thursday'] as const;

const SLOTS: Slot[] = [
  // ---- Saturday / Monday / Wednesday -------------------------------------
  ...weekdayRun({ branch: 'faiyum', classType: 'fitness', trainer: null, startTime: '09:00' }, MORNING_DAYS),
  ...weekdayRun({ branch: 'faiyum', classType: 'aerobic', trainer: null, startTime: '10:00' }, MORNING_DAYS),
  ...weekdayRun({ branch: 'faiyum', classType: 'belly-dance', trainer: null, startTime: '12:00' }, MORNING_DAYS),
  ...weekdayRun({ branch: 'faiyum', classType: 'core-glutes', trainer: null, startTime: '17:00' }, MORNING_DAYS),
  ...weekdayRun({ branch: 'faiyum', classType: 'zumba', trainer: null, startTime: '18:00' }, MORNING_DAYS),

  // Saturday and Wednesday only — Monday's 4:00 PM cell is empty.
  ...weekdayRun({ branch: 'faiyum', classType: 'kick-boxing', trainer: null, startTime: '16:00' }, ['saturday', 'wednesday']),

  // ---- Sunday / Tuesday / Thursday ---------------------------------------
  ...weekdayRun({ branch: 'faiyum', classType: 'core-glutes', trainer: null, startTime: '11:00' }, EVENING_DAYS),
  ...weekdayRun({ branch: 'faiyum', classType: 'aerobic', trainer: null, startTime: '17:00' }, EVENING_DAYS),
  ...weekdayRun({ branch: 'faiyum', classType: 'fitness', trainer: null, startTime: '18:00' }, EVENING_DAYS),
  ...weekdayRun({ branch: 'faiyum', classType: 'belly-dance', trainer: null, startTime: '20:00' }, EVENING_DAYS),
];

async function main() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('MONGODB_URI is not set. Put it in Backend/.env.');
    process.exit(1);
  }

  await connect(uri);

  const BranchModel = model(Branch.name, BranchSchema);
  const ClassTypeModel = model(ClassType.name, ClassTypeSchema);
  const TrainerModel = model(Trainer.name, TrainerSchema);
  const RuleModel = model(RecurrenceRule.name, RecurrenceRuleSchema);
  const SessionModel = model(ClassSession.name, ClassSessionSchema);
  const BookingModel = model(Booking.name, BookingSchema);

  const branches = new Map(
    (await BranchModel.find().select('_id slug').lean()).map(b => [b.slug, b._id])
  );
  const classTypes = new Map(
    (await ClassTypeModel.find().select('_id slug durationMinutes defaultCapacity').lean()).map(
      c => [c.slug, c]
    )
  );
  const trainers = new Map(
    (await TrainerModel.find().select('_id slug').lean()).map(t => [t.slug, t._id])
  );

  if (branches.size === 0 || classTypes.size === 0) {
    console.error('No branches or class types found. Run "npm run seed:gym" first.');
    process.exit(1);
  }

  if (FRESH) {
    await Promise.all([
      RuleModel.deleteMany({}),
      SessionModel.deleteMany({}),
      BookingModel.deleteMany({}),
    ]);
    console.log('--fresh: cleared rules, sessions and bookings');
  }

  const today = utcToZonedDate(new Date(), GYM_TIMEZONE);
  const lastDay = addLocalDays(today, HORIZON_DAYS);

  let ruleCount = 0;
  let sessionCount = 0;

  for (const slot of SLOTS) {
    const branch = branches.get(slot.branch);
    const classType = classTypes.get(slot.classType);
    if (!branch || !classType) {
      console.warn(`  skipped ${slot.classType} at ${slot.branch} — not seeded`);
      continue;
    }

    const trainer = slot.trainer ? (trainers.get(slot.trainer) ?? null) : null;

    // Matched on what actually makes a slot unique, so re-running updates the
    // same row rather than stacking duplicates on the timetable.
    const rule = await RuleModel.findOneAndUpdate(
      {
        branch,
        classType: classType._id,
        weekday: slot.weekday,
        startTime: slot.startTime,
      },
      {
        $set: {
          trainer,
          durationMinutes: classType.durationMinutes,
          capacity: slot.capacity ?? classType.defaultCapacity,
          room: slot.room ?? null,
          womenOnly: slot.womenOnly ?? false,
          effectiveFrom: today,
          effectiveUntil: null,
          isActive: true,
        },
      },
      { upsert: true, new: true }
    );
    ruleCount += 1;

    // Generate occurrences the same way the service does. Duplicated here
    // rather than imported because the service needs a full Nest context, and
    // a seed script that has to boot the app to run is a seed script people
    // stop running.
    const docs = [];
    let cursor = today;
    for (let guard = 0; guard < 400 && cursor <= lastDay; guard++) {
      const startsAt = zonedTimeToUtc(cursor, slot.startTime, GYM_TIMEZONE);
      if (utcToZonedWeekday(startsAt, GYM_TIMEZONE) === slot.weekday) {
        docs.push({
          classType: classType._id,
          branch,
          trainer,
          startsAt,
          endsAt: new Date(startsAt.getTime() + classType.durationMinutes * 60000),
          localDate: cursor,
          capacity: slot.capacity ?? classType.defaultCapacity,
          bookedCount: 0,
          room: slot.room ?? null,
          womenOnly: slot.womenOnly ?? false,
          status: 'scheduled',
          rule: rule._id,
        });
      }
      cursor = addLocalDays(cursor, 1);
    }

    if (docs.length > 0) {
      try {
        const inserted = await SessionModel.insertMany(docs, { ordered: false });
        sessionCount += inserted.length;
      } catch (err) {
        // Duplicates mean those occurrences already exist, which is the whole
        // point of the unique index. Anything else is a real problem.
        const code = (err as { code?: number }).code;
        if (code !== 11000 && !(err as { writeErrors?: unknown[] }).writeErrors) {
          throw err;
        }
        sessionCount += (err as { insertedDocs?: unknown[] }).insertedDocs?.length ?? 0;
      }
    }
  }

  console.log(`recurring slots : ${ruleCount}`);
  console.log(`sessions        : ${sessionCount} (next ${HORIZON_DAYS} days)`);

  await disconnect();
  console.log('\nSchedule seeded.');
}

main().catch(async err => {
  console.error(err);
  await disconnect();
  process.exit(1);
});
