/**
 * Seeds a believable weekly timetable on top of the gym seed.
 *
 *   npm run seed:schedule
 *
 * Run after seed:gym — it looks up branches, class types and trainers by slug
 * and will tell you plainly if any are missing.
 *
 * Idempotent: rules are matched on the combination that makes one unique
 * (branch, class type, weekday, start time), so re-running updates rather than
 * duplicating. Sessions are generated by the same code the admin screen uses,
 * which is itself idempotent through a unique index.
 *
 * Pass --fresh to clear the timetable first. That deletes bookings too, so it
 * is a development convenience and nothing more.
 */
import { connect, disconnect, model } from 'mongoose';
import * as dotenv from 'dotenv';
import { Branch, BranchSchema } from '@/branches/schemas/branch.schema';
import { ClassType, ClassTypeSchema } from '@/class-types/schemas/class-type.schema';
import { Trainer, TrainerSchema } from '@/trainers/schemas/trainer.schema';
import {
  RecurrenceRule,
  RecurrenceRuleSchema,
  ClassSession,
  ClassSessionSchema,
} from '@/classes/schemas/class-session.schema';
import { Booking, BookingSchema } from '@/bookings/schemas/booking.schema';
import {
  zonedTimeToUtc,
  utcToZonedDate,
  utcToZonedWeekday,
  addLocalDays,
  GYM_TIMEZONE,
} from '@/common/utils/timezone.util';

dotenv.config();

const FRESH = process.argv.includes('--fresh');
const HORIZON_DAYS = 21;

// The shape of a real gym week: early mornings and evenings full, midday
// quieter, weekends later and lighter. Written per branch so the three sites
// do not look like copies of each other.
interface Slot {
  branch: string;
  classType: string;
  trainer: string | null;
  weekday: string;
  startTime: string;
  capacity?: number;
  room?: string;
  womenOnly?: boolean;
}

const WEEKDAYS = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'] as const;

function weekdayRun(base: Omit<Slot, 'weekday'>, days: readonly string[]): Slot[] {
  return days.map(weekday => ({ ...base, weekday }));
}

const SLOTS: Slot[] = [
  // These three blocks were one branch each — New Cairo, Sheikh Zayed and
  // Maadi — back when this file seeded three gyms. There is one gym now, so
  // they are grouped by what they emphasise instead.
  //
  // WORTH KNOWING: rules are upserted on (branch, classType, weekday,
  // startTime), so any two slots that differed only by branch now collide and
  // the later one wins. The timetable is not smaller than it should be by
  // accident — it is three timetables folded onto one gym. Prune it to a real
  // week's schedule when class booking is switched on.
  //
  // --- Conditioning-led ---
  ...weekdayRun(
    {
      branch: 'faiyum',
      classType: 'strength-foundations',
      trainer: 'marcus-vance',
      startTime: '07:00',
      room: 'Studio 1',
    },
    WEEKDAYS
  ),
  ...weekdayRun(
    {
      branch: 'faiyum',
      classType: 'hiit-inferno',
      trainer: 'tarek-zaki',
      startTime: '18:30',
      room: 'Studio 2',
      capacity: 20,
    },
    ['sunday', 'tuesday', 'thursday']
  ),
  ...weekdayRun(
    {
      branch: 'faiyum',
      classType: 'metabolic-conditioning',
      trainer: 'tarek-zaki',
      startTime: '06:30',
      room: 'Studio 2',
    },
    ['monday', 'wednesday']
  ),
  ...weekdayRun(
    {
      branch: 'faiyum',
      classType: 'mobility-core',
      trainer: 'youssef-darwish',
      startTime: '11:00',
      room: 'Studio 3',
      womenOnly: true,
    },
    ['sunday', 'tuesday', 'thursday']
  ),
  ...weekdayRun(
    {
      branch: 'faiyum',
      classType: 'yoga',
      trainer: 'youssef-darwish',
      startTime: '19:30',
      room: 'Studio 3',
    },
    ['monday', 'wednesday']
  ),
  {
    branch: 'faiyum',
    classType: 'boxing',
    trainer: 'omar-hassan',
    weekday: 'saturday',
    startTime: '10:00',
    room: 'Studio 2',
  },
  {
    branch: 'faiyum',
    classType: 'functional-circuit',
    trainer: null,
    weekday: 'saturday',
    startTime: '11:30',
    room: 'Studio 1',
  },
  {
    branch: 'faiyum',
    classType: 'recovery-stretch',
    trainer: 'youssef-darwish',
    weekday: 'friday',
    startTime: '17:00',
    room: 'Studio 3',
  },

  // --- Strength-led ---
  ...weekdayRun(
    {
      branch: 'faiyum',
      classType: 'olympic-lifting',
      trainer: 'david-kim',
      startTime: '17:00',
      capacity: 8,
      room: 'Platform',
    },
    ['monday', 'wednesday']
  ),
  ...weekdayRun(
    {
      branch: 'faiyum',
      classType: 'strength-foundations',
      trainer: 'marcus-vance',
      startTime: '07:30',
      room: 'Studio 1',
    },
    ['sunday', 'tuesday', 'thursday']
  ),
  ...weekdayRun(
    {
      branch: 'faiyum',
      classType: 'functional-circuit',
      trainer: 'karim-fahmy',
      startTime: '11:30',
      womenOnly: true,
      room: 'Studio 2',
    },
    ['monday', 'wednesday']
  ),
  {
    branch: 'faiyum',
    classType: 'boxing',
    trainer: 'omar-hassan',
    weekday: 'saturday',
    startTime: '12:00',
    room: 'Studio 2',
  },

  // --- Calmer: yoga, mobility, recovery ---
  ...weekdayRun(
    {
      branch: 'faiyum',
      classType: 'yoga',
      trainer: 'youssef-darwish',
      startTime: '08:00',
      room: 'Studio',
    },
    ['sunday', 'tuesday', 'thursday']
  ),
  ...weekdayRun(
    {
      branch: 'faiyum',
      classType: 'functional-circuit',
      trainer: 'karim-fahmy',
      startTime: '18:00',
      room: 'Studio',
    },
    ['monday', 'wednesday']
  ),
  {
    branch: 'faiyum',
    classType: 'boxing',
    trainer: 'omar-hassan',
    weekday: 'tuesday',
    startTime: '19:30',
    room: 'Studio',
  },
  {
    branch: 'faiyum',
    classType: 'recovery-stretch',
    trainer: 'youssef-darwish',
    weekday: 'saturday',
    startTime: '09:00',
    room: 'Studio',
  },
  {
    branch: 'faiyum',
    classType: 'mobility-core',
    trainer: 'karim-fahmy',
    weekday: 'saturday',
    startTime: '10:00',
    womenOnly: true,
    room: 'Studio',
  },
];

async function main() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('MONGODB_URI is not set. Put it in Backend/.env.');
    process.exit(1);
  }

  await connect(uri);

  const BranchModel = model(Branch.name, BranchSchema);
  const ClassTypeModel = model(ClassType.name, ClassTypeSchema);
  const TrainerModel = model(Trainer.name, TrainerSchema);
  const RuleModel = model(RecurrenceRule.name, RecurrenceRuleSchema);
  const SessionModel = model(ClassSession.name, ClassSessionSchema);
  const BookingModel = model(Booking.name, BookingSchema);

  const branches = new Map(
    (await BranchModel.find().select('_id slug').lean()).map(b => [b.slug, b._id])
  );
  const classTypes = new Map(
    (await ClassTypeModel.find().select('_id slug durationMinutes defaultCapacity').lean()).map(
      c => [c.slug, c]
    )
  );
  const trainers = new Map(
    (await TrainerModel.find().select('_id slug').lean()).map(t => [t.slug, t._id])
  );

  if (branches.size === 0 || classTypes.size === 0) {
    console.error('No branches or class types found. Run "npm run seed:gym" first.');
    process.exit(1);
  }

  if (FRESH) {
    await Promise.all([
      RuleModel.deleteMany({}),
      SessionModel.deleteMany({}),
      BookingModel.deleteMany({}),
    ]);
    console.log('--fresh: cleared rules, sessions and bookings');
  }

  const today = utcToZonedDate(new Date(), GYM_TIMEZONE);
  const lastDay = addLocalDays(today, HORIZON_DAYS);

  let ruleCount = 0;
  let sessionCount = 0;

  for (const slot of SLOTS) {
    const branch = branches.get(slot.branch);
    const classType = classTypes.get(slot.classType);
    if (!branch || !classType) {
      console.warn(`  skipped ${slot.classType} at ${slot.branch} — not seeded`);
      continue;
    }

    const trainer = slot.trainer ? (trainers.get(slot.trainer) ?? null) : null;

    // Matched on what actually makes a slot unique, so re-running updates the
    // same row rather than stacking duplicates on the timetable.
    const rule = await RuleModel.findOneAndUpdate(
      {
        branch,
        classType: classType._id,
        weekday: slot.weekday,
        startTime: slot.startTime,
      },
      {
        $set: {
          trainer,
          durationMinutes: classType.durationMinutes,
          capacity: slot.capacity ?? classType.defaultCapacity,
          room: slot.room ?? null,
          womenOnly: slot.womenOnly ?? false,
          effectiveFrom: today,
          effectiveUntil: null,
          isActive: true,
        },
      },
      { upsert: true, new: true }
    );
    ruleCount += 1;

    // Generate occurrences the same way the service does. Duplicated here
    // rather than imported because the service needs a full Nest context, and
    // a seed script that has to boot the app to run is a seed script people
    // stop running.
    const docs = [];
    let cursor = today;
    for (let guard = 0; guard < 400 && cursor <= lastDay; guard++) {
      const startsAt = zonedTimeToUtc(cursor, slot.startTime, GYM_TIMEZONE);
      if (utcToZonedWeekday(startsAt, GYM_TIMEZONE) === slot.weekday) {
        docs.push({
          classType: classType._id,
          branch,
          trainer,
          startsAt,
          endsAt: new Date(startsAt.getTime() + classType.durationMinutes * 60000),
          localDate: cursor,
          capacity: slot.capacity ?? classType.defaultCapacity,
          bookedCount: 0,
          room: slot.room ?? null,
          womenOnly: slot.womenOnly ?? false,
          status: 'scheduled',
          rule: rule._id,
        });
      }
      cursor = addLocalDays(cursor, 1);
    }

    if (docs.length > 0) {
      try {
        const inserted = await SessionModel.insertMany(docs, { ordered: false });
        sessionCount += inserted.length;
      } catch (err) {
        // Duplicates mean those occurrences already exist, which is the whole
        // point of the unique index. Anything else is a real problem.
        const code = (err as { code?: number }).code;
        if (code !== 11000 && !(err as { writeErrors?: unknown[] }).writeErrors) {
          throw err;
        }
        sessionCount += (err as { insertedDocs?: unknown[] }).insertedDocs?.length ?? 0;
      }
    }
  }

  console.log(`recurring slots : ${ruleCount}`);
  console.log(`sessions        : ${sessionCount} (next ${HORIZON_DAYS} days)`);

  await disconnect();
  console.log('\nSchedule seeded.');
}

main().catch(async err => {
  console.error(err);
  await disconnect();
  process.exit(1);
});
